import { FormEvent, useMemo, useState } from "react";
import { ArrowRight, CalendarDays, Check, ClipboardList, Clock3, Heart, MapPin, PackageCheck, Phone, QrCode, ShieldCheck, Store, UserRound } from "lucide-react";
import { Link, useSearchParams } from "react-router-dom";
import { useApp, getOrderFulfillmentLabel } from "../app/AppContext";
import { Breadcrumbs } from "../components/SiteLayout";
import { EmptyState, Field, ProductCard, SectionHeading } from "../components/Ui";

export function OrderSuccessPage() {
  const [params] = useSearchParams();
  const orderNumber = params.get("order") ?? "RS-2026-DEMO";
  const { orders, settings } = useApp();
  const order = orders.find((item) => item.orderNumber === orderNumber);
  return <section className="section"><div className="container-narrow"><div className="order-success"><div className="success-icon"><Check size={32} /></div><div className="eyebrow" style={{ color: "var(--mint)" }}>Order received</div><h1>You're all set.</h1><p>{order?.paymentMethod === "razorpay" ? "Your order is reserved and waiting for secure payment verification." : `We’ll get your Rider Shoes order moving and keep you posted at ${order?.customer.phone ?? settings.supportPhone}.`}</p><div className="order-number">{orderNumber}</div><div style={{ display: "flex", gap: 9, justifyContent: "center", flexWrap: "wrap" }}><Link className="button button-light" to="/orders">Track order <ArrowRight size={14} /></Link><Link className="button button-dark" to="/shop">Keep exploring</Link></div></div></div></section>;
}

export function OrdersPage() {
  const { orders } = useApp();
  return <><div className="page-hero"><div className="container-wide"><div className="eyebrow">Your account</div><h1 className="display-title">Orders</h1><p>Everything you have ordered, with the next step always visible.</p></div></div><Breadcrumbs current="Orders" /><section className="section"><div className="container-narrow">{orders.length === 0 ? <div className="cart-list"><EmptyState icon={ClipboardList} title="No orders yet" description="Your first great pair is only a few clicks away." action={<Link className="button button-primary" to="/shop">Shop the collection <ArrowRight size={14} /></Link>} /></div> : <div style={{ display: "grid", gap: 13 }}>{orders.slice().reverse().map((order) => <OrderCard key={order.id} order={order} />)}</div>}</div></section></>;
}

function OrderCard({ order }: { order: ReturnType<typeof useApp>["orders"][number] }) {
  const steps = ["pending", "confirmed", "processing", "shipped", "delivered"];
  const current = Math.max(0, steps.indexOf(order.status));
  return <article className="form-card"><div style={{ display: "flex", justifyContent: "space-between", gap: 14, alignItems: "start", flexWrap: "wrap" }}><div><div className="eyebrow">{new Date(order.createdAt).toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" })}</div><h2 style={{ margin: "7px 0 4px" }}>{order.orderNumber}</h2><p style={{ margin: 0, color: "var(--muted)", fontSize: ".74rem" }}>{order.items.length} {order.items.length === 1 ? "item" : "items"} · {order.paymentMethod === "cod" ? "Cash on delivery" : "Razorpay"}</p></div><div style={{ textAlign: "right" }}><strong style={{ fontSize: "1.05rem" }}>₹{order.totalAmount.toLocaleString("en-IN")}</strong><div className={`status-dot ${order.status === "cancelled" ? "cancelled" : order.status === "pending" ? "pending" : ""}`} style={{ marginTop: 8 }}>{order.status === "pending" ? "Payment pending" : getOrderFulfillmentLabel(order.fulfillmentStatus)}</div></div></div><div style={{ display: "grid", gridTemplateColumns: "repeat(5, 1fr)", gap: 5, margin: "27px 0 8px" }}>{steps.map((step, index) => <div key={step} style={{ height: 5, borderRadius: 99, background: index <= current ? "var(--coral)" : "var(--mist)" }} />)}</div><div style={{ display: "flex", justifyContent: "space-between", color: "var(--muted)", fontSize: ".64rem" }}><span>Placed</span><span>Confirmed</span><span>Preparing</span><span>On the way</span><span>Delivered</span></div><div style={{ display: "flex", gap: 9, marginTop: 20, flexWrap: "wrap" }}>{order.items.slice(0, 3).map((item) => <Link key={item.id} to={item.productSlug ? `/product/${item.productSlug}` : "/shop"} style={{ display: "flex", alignItems: "center", gap: 8, padding: 7, borderRadius: 10, background: "var(--mist)", fontSize: ".68rem" }}><img src={item.imageUrl} alt="" style={{ width: 33, height: 28, objectFit: "cover", borderRadius: 6 }} />{item.productName}</Link>)}</div></article>;
}

export function WishlistPage() {
  const { products, wishlist } = useApp();
  const savedProducts = products.filter((product) => wishlist.includes(product.id));
  return <><div className="page-hero"><div className="container-wide"><div className="eyebrow">Your edit</div><h1 className="display-title">Wishlist</h1><p>Save the pairs you want to come back to when the timing feels right.</p></div></div><Breadcrumbs current="Wishlist" /><section className="section"><div className="container-wide">{savedProducts.length === 0 ? <div className="cart-list"><EmptyState icon={Heart} title="Nothing saved yet" description="Tap the heart on any pair to keep it close." action={<Link className="button button-primary" to="/shop">Find your pair <ArrowRight size={14} /></Link>} /></div> : <div className="product-grid">{savedProducts.map((product, index) => <ProductCard key={product.id} product={product} index={index} />)}</div>}</div></section></>;
}

export function StoreVisitPage() {
  const { products, saveVisit, settings } = useApp();
  const [submittedId, setSubmittedId] = useState<string | null>(null);
  const [form, setForm] = useState({ name: "", phone: "", date: "", time: "", productId: "", whatsapp: "" });
  const submit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const visit = saveVisit({ path: "/store-visit", referrer: document.referrer || null, userAgent: navigator.userAgent, profileId: null, sessionIdHash: null, metadata: { name: form.name, phone: form.phone, visitDate: form.date, visitTime: form.time, productId: form.productId, whatsapp: form.whatsapp } });
    setSubmittedId(visit.id);
  };
  if (submittedId) return <section className="section"><div className="container-narrow"><div className="visit-panel"><div className="visit-copy"><div className="eyebrow">Your visit is saved</div><h2 className="display-title">See you in Dhanera.</h2><p>Show this visit ID when you arrive and our team will unlock your configured store-only offer.</p><div className="visit-id">{submittedId.replace("visit-", "RS-VISIT-").slice(0, 21).toUpperCase()}</div></div><div className="visit-form visit-result"><div className="qr-placeholder" aria-label="Demo QR code placeholder"><QrCode size={98} color="transparent" /></div><strong>Store visit pass</strong><span style={{ color: "rgba(255,255,255,.58)", fontSize: ".74rem" }}>{settings.addressLine1}, {settings.city}<br />{settings.storeHours}</span><button className="button button-light" onClick={() => setSubmittedId(null)}>Register another visit</button></div></div></div></section>;
  return <><div className="page-hero"><div className="container-wide"><div className="eyebrow">In-person, made easy</div><h1 className="display-title">Visit the store.<br /><span style={{ color: "var(--coral)" }}>Get extra.</span></h1><p>Register your visit before you arrive. Try the pairs you are considering and unlock a store-only offer.</p></div></div><Breadcrumbs current="Store visit" /><section className="section"><div className="container-wide"><div className="visit-panel"><div className="visit-copy"><div className="eyebrow">Rider Shoes · Dhanera</div><h2 className="display-title">Make time for the in-person fit.</h2><p>Our team can help with fit, movement, styling, and finding the pair that feels right. No pressure, just good shoes.</p><div className="editorial-list"><span><UserRound size={15} /> Personal fit guidance</span><span><ShoppingBagIcon /> Choose from the full edit</span><span><MapPin size={15} /> {settings.addressLine1}, {settings.city}</span><span><Clock3 size={15} /> {settings.storeHours}</span></div></div><form className="visit-form" onSubmit={submit}><h2 style={{ marginTop: 0 }}>Register your visit</h2><div className="form-grid"><Field label="Your name" name="visit-name" value={form.name} onChange={(value) => setForm((current) => ({ ...current, name: value }))} required placeholder="Name" /><Field label="Mobile number" name="visit-phone" value={form.phone} onChange={(value) => setForm((current) => ({ ...current, phone: value }))} required placeholder="99791 31767" /><Field label="Preferred date" name="visit-date" type="date" value={form.date} onChange={(value) => setForm((current) => ({ ...current, date: value }))} required /><Field label="Preferred time" name="visit-time" type="time" value={form.time} onChange={(value) => setForm((current) => ({ ...current, time: value }))} required /><div className="field full"><label htmlFor="visit-product">What are you looking for?</label><select id="visit-product" value={form.productId} onChange={(event) => setForm((current) => ({ ...current, productId: event.target.value }))}><option value="">I am open to recommendations</option>{products.map((product) => <option key={product.id} value={product.id}>{product.name}</option>)}</select></div><Field label="WhatsApp number (optional)" name="visit-whatsapp" value={form.whatsapp} onChange={(value) => setForm((current) => ({ ...current, whatsapp: value }))} placeholder="Same as mobile is fine" /><div className="field" style={{ alignContent: "end" }}><button className="button button-light button-block" type="submit">Get my visit pass <ArrowRight size={14} /></button></div></div><p style={{ marginBottom: 0, color: "rgba(255,255,255,.48)", fontSize: ".67rem", lineHeight: 1.5 }}>We only use these details to coordinate your visit. You can request deletion at any time.</p></form></div></div></section></>;
}

function ShoppingBagIcon() { return <PackageCheck size={15} />; }

export function AccountPage() {
  const { orders, wishlist, storeVisits, settings } = useApp();
  const total = orders.reduce((sum, order) => sum + order.totalAmount, 0);
  return <><div className="page-hero"><div className="container-wide"><div className="eyebrow">Welcome back</div><h1 className="display-title">Your account</h1><p>A simple home for orders, saved pairs, and store visits.</p></div></div><Breadcrumbs current="Account" /><section className="section"><div className="container-wide"><div className="metric-grid"><div className="metric-card"><div className="metric-label">Orders</div><strong>{orders.length}</strong><div className="metric-change"><ClipboardList size={12} /> all time</div></div><div className="metric-card"><div className="metric-label">Saved pairs</div><strong>{wishlist.length}</strong><div className="metric-change"><Heart size={12} /> wishlist</div></div><div className="metric-card"><div className="metric-label">Store visits</div><strong>{storeVisits.length}</strong><div className="metric-change"><Store size={12} /> registered</div></div><div className="metric-card"><div className="metric-label">Total spent</div><strong>₹{total.toLocaleString("en-IN")}</strong><div className="metric-change"><ShieldCheck size={12} /> secure</div></div></div><div className="section-tight" style={{ paddingBottom: 0 }}><div className="section-head"><div><div className="eyebrow">Quick links</div><h2 className="display-title">Keep moving.</h2></div></div><div className="category-grid" style={{ gridTemplateColumns: "repeat(3, 1fr)" }}><Link className="category-card" to="/orders"><div style={{ height: "100%", padding: 22, background: "linear-gradient(140deg, #d6e4df, #fff)" }}><ClipboardList size={26} color="var(--coral)" /><div className="category-copy" style={{ color: "var(--ink)" }}><h3 style={{ color: "var(--ink)" }}>Track an order</h3><p style={{ color: "var(--muted)" }}>See where your next pair is.</p></div></div></Link><Link className="category-card" to="/wishlist"><div style={{ height: "100%", padding: 22, background: "linear-gradient(140deg, #f5dfe2, #fff)" }}><Heart size={26} color="var(--coral)" /><div className="category-copy" style={{ color: "var(--ink)" }}><h3 style={{ color: "var(--ink)" }}>Your wishlist</h3><p style={{ color: "var(--muted)" }}>The pairs you are thinking about.</p></div></div></Link><Link className="category-card" to="/store-visit"><div style={{ height: "100%", padding: 22, background: "linear-gradient(140deg, #dce4ef, #fff)" }}><Store size={26} color="var(--coral)" /><div className="category-copy" style={{ color: "var(--ink)" }}><h3 style={{ color: "var(--ink)" }}>Plan a visit</h3><p style={{ color: "var(--muted)" }}>{settings.city} · get extra in-store.</p></div></div></Link></div></div></div></section></>;
}

export function StaticPage({ kind }: { kind: "about" | "contact" | "offers" | "privacy" | "terms" | "refund" }) {
  const { settings, products } = useApp();
  const content = {
    about: { eyebrow: "The Rider story", title: "Made for the way you move.", text: "Rider Shoes is a considered local footwear store in Dhanera, built around a simple idea: good shoes should make more of your day possible. We look for comfort, honest details, and pairs that earn their place in your rotation." },
    contact: { eyebrow: "Come say hello", title: "We are here for your next step.", text: `Visit us in ${settings.city}, call ${settings.supportPhone}, or send a message. Our team can help with fit, availability, delivery, or a store appointment.` },
    offers: { eyebrow: "Current edit", title: "A little more reason to move.", text: "Browse our featured pairs and ask the team about current store-only offers. Online coupons are configured by the admin portal and always show clearly at checkout." },
    privacy: { eyebrow: "Rider Shoes", title: "Privacy, without the fine print fog.", text: "We use your details to fulfil orders, answer questions, and coordinate visits. Sensitive payment data stays with the payment provider. You can request access or deletion by contacting the store." },
    terms: { eyebrow: "Rider Shoes", title: "The simple terms.", text: "Products, prices, availability, delivery estimates, returns, and offers are subject to confirmation at checkout. We will contact you if a detail changes before fulfilment." },
    refund: { eyebrow: "Returns & refunds", title: "If it is not the right fit.", text: `Contact us within ${settings.returnsWindowDays} days of delivery for return support. Items should be unworn, in original condition, and accompanied by the order details. Our team will guide you through the next step.` },
  }[kind];
  return <><div className="page-hero"><div className="container-wide"><div className="eyebrow">{content.eyebrow}</div><h1 className="display-title">{content.title}</h1><p>{content.text}</p></div></div><Breadcrumbs current={content.title} /><section className="section"><div className="container-narrow"><div className="form-card"><p style={{ color: "var(--ink-soft)", lineHeight: 1.8, fontSize: ".9rem" }}>{content.text}</p>{kind === "contact" && <div className="detail-meta" style={{ marginTop: 28 }}><div className="meta-tile"><Phone size={16} /><span>{settings.supportPhone}</span></div><div className="meta-tile"><MapPin size={16} /><span>{settings.addressLine1}, {settings.city}</span></div><div className="meta-tile"><CalendarDays size={16} /><span>{settings.storeHours}</span></div></div>}{kind === "offers" && <><SectionHeading eyebrow="Featured now" title="Find your next favourite." /><div className="product-grid">{products.filter((product) => product.compareAtPrice).slice(0, 4).map((product, index) => <ProductCard key={product.id} product={product} index={index} />)}</div></>}{kind === "contact" && <Link className="button button-primary" style={{ marginTop: 24 }} to="/store-visit">Register a store visit <ArrowRight size={14} /></Link>}</div></div></section></>;
}
