import { useEffect, useMemo, useState } from "react";
import { ArrowRight, Check, Clock3, MapPin, Minus, Plus, RotateCcw, ShieldCheck, Truck, X } from "lucide-react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { useApp } from "../app/AppContext";
import { Breadcrumbs } from "../components/SiteLayout";
import { ProductCard, SectionHeading, Stars } from "../components/Ui";
import { getSupabaseClient } from "../lib/supabase";

const isUuid=(value:string)=>/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value);

export function ProductPage(){
  const {slug}=useParams(); const navigate=useNavigate();
  const {products,cart,addToCart,settings}=useApp(); const product=products.find(x=>x.slug===slug);
  const [imageIndex,setImageIndex]=useState(0),[size,setSize]=useState(""),[color,setColor]=useState(""),[quantity,setQuantity]=useState(1),[pincode,setPincode]=useState(""),[deliveryMessage,setDeliveryMessage]=useState("");
  const [visitOpen,setVisitOpen]=useState(false),[visit,setVisit]=useState({name:"",phone:"",email:""}),[visitBusy,setVisitBusy]=useState(false),[visitResult,setVisitResult]=useState(""),[visitError,setVisitError]=useState("");
  const [visitEnabled,setVisitEnabled]=useState(false),[visitDiscount,setVisitDiscount]=useState(0),[visitType,setVisitType]=useState<"percent"|"fixed">("percent");
  useEffect(()=>{const c=getSupabaseClient();if(!c)return;c.from("business_settings").select("setting_value").eq("setting_key","store.settings").maybeSingle().then(({data})=>{const s=(data?.setting_value||{}) as any;setVisitEnabled(s.storeVisitEnabled!==false);setVisitDiscount(Number(s.storeVisitDiscount||0));setVisitType(s.storeVisitDiscountType==="fixed"?"fixed":"percent")})},[]);
  useEffect(()=>{if(product){setColor(product.colors[0]||"");setSize("")}},[product?.id]);
  if(!product)return <div className="section"><div className="container-narrow"><div className="empty-state"><h2>That pair has moved on.</h2><Link className="button button-primary" to="/shop">Back to shop <ArrowRight size={14}/></Link></div></div></div>;
  const variant=useMemo(()=>size?product.variants.find(v=>v.size===size&&(!color||v.color===color)):undefined,[color,product.variants,size]);
  const inCart=variant?cart.some(x=>x.productId===product.id&&x.variantId===variant.id):false;
  const discount=product.compareAtPrice&&product.compareAtPrice>product.price?Math.round((1-product.price/product.compareAtPrice)*100):0;
  const related=products.filter(x=>x.id!==product.id&&x.categoryIds.some(id=>product.categoryIds.includes(id))).slice(0,4);
  const checkDelivery=()=>setDeliveryMessage(pincode.length===6?`We will confirm delivery to ${pincode} at checkout.`:"Enter a valid 6-digit pincode.");
  const addOrCheckout=()=>{if(!size){setDeliveryMessage("Please select a size before adding to cart.");return}if(!variant){setDeliveryMessage("That size is not available.");return}if(inCart){navigate("/cart");return}addToCart(product,variant,quantity)};
  const openVisit=()=>{setVisitOpen(true);setVisitResult("");setVisitError("");setVisit({name:"",phone:"",email:""})};
  const register=async()=>{
    const name=visit.name.trim(),phone=visit.phone.replace(/\D/g,"").slice(0,10),email=visit.email.trim();
    setVisitError("");setVisitResult("");
    if(name.length<2){setVisitError("Please enter your name.");return}
    if(phone.length!==10){setVisitError("Please enter a valid 10-digit mobile number.");return}
    if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)){setVisitError("Please enter a valid email address or leave it blank.");return}
    setVisitBusy(true);
    try{
      const c=getSupabaseClient();if(!c)throw Error("Store registration is unavailable right now.");
      let productId:string|null=isUuid(product.id)?product.id:null;
      if(!productId){const {data}=await c.from("products").select("id").eq("slug",product.slug).maybeSingle();productId=data?.id||null;}
      const {data,error}=await c.rpc("register_store_visit",{_name:name,_phone:phone,_email:email||null,_product_id:productId,_visit_date:null,_visit_time:null});
      if(error)throw error;
      const ref=String((data as any)?.referenceNumber||"");if(!ref)throw Error("The store could not generate a visit reference. Please try again.");
      try{localStorage.setItem("rider-shoes:store-visit-reference",ref)}catch{}
      setVisitResult(ref);setVisit({name:"",phone:"",email:""});
    }catch(e){setVisitError(e instanceof Error?e.message:"Unable to register your store visit")}finally{setVisitBusy(false)}
  };
  return <>
    <Breadcrumbs current={product.name}/><section className="section-tight"><div className="container-wide"><div className="product-detail">
      <div className="gallery"><div className="thumbs">{product.images.map((image,i)=><button key={image.id} className={`thumb ${imageIndex===i?"active":""}`} onClick={()=>setImageIndex(i)}><img src={image.url} alt={`${product.name} view ${i+1}`}/></button>)}</div><div className="gallery-main"><img src={product.images[imageIndex]?.url||product.imageUrl} alt={product.name}/></div></div>
      <div className="detail-copy"><div className="product-brand">{product.brand?.name||"Rider collection"} · {product.badge||"Everyday movement"}</div><h1>{product.name}</h1><Stars rating={product.rating||0} reviewCount={product.reviewCount}/><p className="lead">{product.description}</p><div className="detail-price"><span className="price">₹{product.price.toLocaleString("en-IN")}</span>{product.compareAtPrice&&<span className="compare">₹{product.compareAtPrice.toLocaleString("en-IN")}</span>}{discount>0&&<span className="discount">{discount}% off</span>}</div>
        {product.colors.length>0&&<div className="detail-block"><div className="detail-label"><span>Color</span><span>{color}</span></div><div className="color-list">{product.colors.map(c=><button key={c} className={`color-option ${color===c?"active":""}`} onClick={()=>setColor(c)}>{c}</button>)}</div></div>}
        <div className="detail-block"><div className="detail-label"><span>Size</span><strong style={{color:"var(--coral)"}}>{size?`Selected ${size}`:"Select a size"}</strong></div><div className="size-list">{product.sizes.map(s=><button key={s} className={`size-option ${size===s?"active":""}`} onClick={()=>{setSize(s);setDeliveryMessage("")}}>{s}</button>)}</div></div>
        <div className="detail-block" style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:15}}><div><div className="detail-label" style={{marginBottom:8}}>Quantity</div><div className="quantity-control"><button onClick={()=>setQuantity(x=>Math.max(1,x-1))}><Minus size={14}/></button><strong>{quantity}</strong><button onClick={()=>setQuantity(x=>Math.min(5,x+1))}><Plus size={14}/></button></div></div><span style={{display:"inline-flex",alignItems:"center",gap:7,color:product.inStock?"#31815c":"var(--coral)",fontSize:".75rem",fontWeight:800}}><Check size={15}/>{product.inStock?"In stock":"Unavailable"}</span></div>
        <div className="detail-actions"><button className="button button-primary" onClick={addOrCheckout} disabled={!product.inStock}>{inCart?"Checkout":"Add to cart"}<ArrowRight size={15}/></button>{visitEnabled&&<button className="button button-outline" onClick={openVisit} disabled={!product.inStock}>Buy from Store</button>}</div>
        {deliveryMessage&&<div className="error-text" style={{marginTop:10}}>{deliveryMessage}</div>}
        <div className="detail-block"><div className="detail-label"><span>Delivery checker</span><span>{settings.deliveryEstimate}</span></div><div style={{display:"flex",gap:8}}><input value={pincode} onChange={e=>setPincode(e.target.value.replace(/\D/g,"").slice(0,6))} placeholder="Enter pincode" inputMode="numeric" style={{flex:1,minHeight:42,border:"1px solid var(--line)",borderRadius:11,padding:"0 12px"}}/><button className="button button-dark button-small" onClick={checkDelivery}>Check</button></div></div>
        {visitEnabled&&visitDiscount>0&&<div className="detail-block" style={{background:"#fff7ef",borderRadius:12,padding:12}}><strong>Store visit offer</strong><div style={{fontSize:".72rem",marginTop:5,color:"var(--muted)"}}>Register a store visit and receive {visitType==="fixed"?`₹${visitDiscount}`:`${visitDiscount}%`} extra discount at the store.</div></div>}
        <div className="detail-meta"><div className="meta-tile"><Truck size={16}/><span>Fast delivery</span></div><div className="meta-tile"><RotateCcw size={16}/><span>{settings.returnsWindowDays}-day returns</span></div><div className="meta-tile"><ShieldCheck size={16}/><span>Secure checkout</span></div></div>
      </div></div></div></section>
    <section className="section-tight"><div className="container-wide"><SectionHeading eyebrow="Keep exploring" title="You may also like" description="Similar silhouettes, different energy."/>{related.length?<div className="product-grid">{related.map((item,i)=><ProductCard key={item.id} product={item} index={i}/>)}</div>:<p style={{color:"var(--muted)"}}>More pairs are arriving soon.</p>}</div></section>
    {visitOpen&&<div className="visit-modal-backdrop" role="dialog" aria-modal="true" aria-label="Register store visit" onMouseDown={e=>{if(e.currentTarget===e.target)setVisitOpen(false)}}><div className="visit-modal-card"><button className="visit-modal-close" aria-label="Close" onClick={()=>setVisitOpen(false)}><X size={19}/></button><div className="visit-modal-top"><div className="visit-modal-icon"><MapPin size={20}/></div><div><div className="eyebrow">BUY FROM STORE</div><h2>Reserve your store visit</h2><p>Get your unique reference for <strong>{product.name}</strong>.</p></div></div><div className="visit-modal-offer"><div><span>Store visit benefit</span><strong>{visitType==="fixed"?`₹${visitDiscount} OFF`:`${visitDiscount}% OFF`}</strong></div><small>Applied at store checkout after verification</small></div>{visitResult.startsWith("RSV-")?<div className="visit-confirm"><div className="visit-confirm-label">YOUR UNIQUE REFERENCE</div><strong>{visitResult}</strong><p>Show this reference and the same mobile number at Rider Shoes checkout. It can be redeemed once before it expires.</p><button className="button button-primary button-block" onClick={()=>setVisitOpen(false)}>Done</button></div>:<><div className="visit-form-grid"><label><span>Name</span><input autoFocus placeholder="Your full name" value={visit.name} onChange={e=>setVisit({...visit,name:e.target.value})}/></label><label><span>Mobile number</span><input inputMode="numeric" placeholder="10-digit mobile" value={visit.phone} onChange={e=>setVisit({...visit,phone:e.target.value.replace(/\D/g,"").slice(0,10)})}/></label><label className="full"><span>Email <em>optional</em></span><input type="email" placeholder="you@example.com" value={visit.email} onChange={e=>setVisit({...visit,email:e.target.value})}/></label></div>{visitError&&<div className="visit-modal-error">{visitError}</div>}<div className="visit-modal-note"><Clock3 size={14}/> Your reference is valid for the period configured by Rider Shoes.</div><button className="button button-primary button-block" style={{marginTop:14}} onClick={register} disabled={visitBusy||!visit.name.trim()||visit.phone.replace(/\D/g,"").length!==10}>{visitBusy?"Creating reference…":"Register visit & get reference"}<ArrowRight size={15}/></button></>}</div></div>}
    <style>{visitModalStyles}</style>
  </>;
}

const visitModalStyles=`
.visit-modal-backdrop{position:fixed;inset:0;z-index:200;display:grid;place-items:center;padding:18px;background:rgba(8,14,16,.68);backdrop-filter:blur(8px);animation:visitFade .18s ease}
.visit-modal-card{position:relative;width:min(520px,100%);max-height:min(720px,calc(100dvh - 28px));overflow:auto;border:1px solid rgba(255,255,255,.55);border-radius:24px;padding:25px;background:#fff;box-shadow:0 35px 100px rgba(0,0,0,.34);animation:visitUp .22s ease}
.visit-modal-close{position:absolute;right:14px;top:14px;width:38px;height:38px;border:1px solid #e2e8e6;border-radius:12px;background:#f7f9f8;color:#314043;display:grid;place-items:center}.visit-modal-close:hover{color:var(--coral);border-color:var(--coral)}
.visit-modal-top{display:flex;gap:14px;align-items:flex-start;padding-right:38px}.visit-modal-icon{width:44px;height:44px;flex:0 0 44px;border-radius:14px;display:grid;place-items:center;color:#fff;background:linear-gradient(135deg,#ef6b4f,#d83d4b);box-shadow:0 10px 25px rgba(232,60,74,.22)}
.visit-modal-top h2{margin:5px 0 5px;font-family:"Space Grotesk",sans-serif;letter-spacing:-.045em;font-size:28px;line-height:1.02}.visit-modal-top p{margin:0;color:var(--muted);font-size:.76rem;line-height:1.5}
.visit-modal-offer{margin:20px 0 17px;padding:15px 16px;border:1px solid #f2d7cf;border-radius:16px;background:linear-gradient(135deg,#fff7f3,#fff)}.visit-modal-offer div{display:flex;align-items:center;justify-content:space-between;gap:12px}.visit-modal-offer span{font-size:.68rem;font-weight:800;text-transform:uppercase;letter-spacing:.12em;color:#7c6a65}.visit-modal-offer strong{font-size:1.25rem;color:var(--coral)}.visit-modal-offer small{display:block;margin-top:5px;color:var(--muted);font-size:.65rem}
.visit-form-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.visit-form-grid label{display:grid;gap:6px}.visit-form-grid label.full{grid-column:1/-1}.visit-form-grid span{font-size:.68rem;font-weight:800;color:#344447}.visit-form-grid em{font-style:normal;color:#8b9795;font-weight:600}.visit-form-grid input{width:100%;min-height:46px;border:1px solid #dce4e2;border-radius:12px;padding:0 13px;background:#fbfcfc;color:#172124;outline:none}.visit-form-grid input:focus{border-color:#ef6b4f;box-shadow:0 0 0 3px rgba(239,107,79,.11);background:#fff}.visit-modal-note{display:flex;gap:7px;align-items:flex-start;margin-top:13px;color:#788684;font-size:.64rem;line-height:1.45}.visit-modal-error{margin-top:11px;padding:10px 12px;border-radius:10px;background:#fff0f1;color:#c32e3c;font-size:.68rem;font-weight:700}.visit-confirm{margin-top:8px;padding:20px;border-radius:17px;text-align:center;background:#eef8f2;border:1px solid #cde8d9}.visit-confirm-label{font-size:.61rem;letter-spacing:.16em;font-weight:900;color:#4b7b62}.visit-confirm>strong{display:block;margin:7px 0 4px;font:900 1.65rem "DM Mono",monospace;letter-spacing:.06em;color:#173a2a}.visit-confirm p{margin:0 auto 15px;max-width:390px;color:#5e7469;font-size:.69rem;line-height:1.55}
@keyframes visitFade{from{opacity:0}to{opacity:1}}@keyframes visitUp{from{opacity:0;transform:translateY(12px) scale(.985)}to{opacity:1;transform:none}}
@media(max-width:560px){.visit-modal-backdrop{padding:10px;align-items:end}.visit-modal-card{border-radius:22px;padding:20px 16px;max-height:calc(100dvh - 20px)}.visit-modal-top h2{font-size:24px}.visit-form-grid{grid-template-columns:1fr}.visit-form-grid label.full{grid-column:auto}.visit-modal-offer{margin:16px 0 14px}}
`;