import { FormEvent, useState } from "react";
import { ArrowRight, Clock3, MapPin, PackageCheck, QrCode, UserRound } from "lucide-react";
import { useApp } from "../app/AppContext";
import { Breadcrumbs } from "../components/SiteLayout";
import { Field } from "../components/Ui";
import { getSupabaseClient } from "../lib/supabase";
export function StoreVisitPageV2(){
 const {products,settings}=useApp();const [form,setForm]=useState({name:"",phone:"",email:"",date:"",time:"",productId:""});const [pass,setPass]=useState<any>(null);const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 const submit=async(e:FormEvent)=>{e.preventDefault();setError("");setBusy(true);try{const client=getSupabaseClient();if(!client)throw Error("Store visit service is unavailable.");const {data,error:e}=await client.rpc("register_store_visit",{_name:form.name,_phone:form.phone,_email:form.email||null,_product_id:form.productId||null,_visit_date:form.date||null,_visit_time:form.time||null});if(e)throw e;if(!data)throw Error("Unable to register your visit.");try{localStorage.setItem("rider-shoes:store-visit-reference",data.referenceNumber)}catch{}setPass(data)}catch(x){setError(x instanceof Error?x.message:"Unable to register your visit")}finally{setBusy(false)}};
 if(settings.storeVisitEnabled===false)return <section className="section"><div className="container-narrow"><div className="empty-state"><div className="eyebrow">Store visit</div><h2>Visit registration is currently closed.</h2><p>Please contact the store for an appointment.</p></div></div></section>;
 if(pass)return <section className="section"><div className="container-narrow"><div className="visit-success"><div className="eyebrow">Visit confirmed</div><h1>{pass.referenceNumber}</h1><p>Show this reference at Rider Shoes checkout in Dhanera. It is linked to your mobile number and can be redeemed once.</p><div className="visit-discount">{pass.discountType==="fixed"?`₹${pass.discountValue} off`:`${pass.discountValue}% off`} <small>store visit offer</small></div><div className="visit-pass-meta"><span><MapPin size={14}/>{settings.addressLine1}, {settings.city}</span><span><Clock3 size={14}/>{settings.storeHours}</span></div><div className="visit-qr"><QrCode size={74}/><span>Reference: {pass.referenceNumber}</span></div><button className="button button-primary" onClick={()=>setPass(null)}>Register another visit</button></div></div></section>;
 return <><div className="page-hero"><div className="container-wide"><div className="eyebrow">In-person, made easy</div><h1 className="display-title">Buy from the store.<br/><span style={{color:"var(--coral)"}}>Get extra.</span></h1><p>Register for a store visit and receive the discount configured by Rider Shoes admin.</p></div></div><Breadcrumbs current="Store visit"/><section className="section"><div className="container-wide"><div className="visit-panel"><div className="visit-copy"><div className="eyebrow">Rider Shoes · {settings.city}</div><h2 className="display-title">Make time for the in-person fit.</h2><p>Bring your reference when you visit. Your offer is tied to your mobile number and, when selected, the product you want to see.</p><div className="editorial-list"><span><UserRound size={15}/>Personal fit guidance</span><span><PackageCheck size={15}/>Store-only offer</span><span><MapPin size={15}/>{settings.addressLine1}, {settings.city}</span><span><Clock3 size={15}/>{settings.storeHours}</span></div></div><form className="visit-form" onSubmit={submit}><h2 style={{marginTop:0}}>Register your visit</h2><div className="form-grid"><Field label="Your name" name="visit-name" value={form.name} onChange={v=>setForm(x=>({...x,name:v}))} required placeholder="Name"/><Field label="Mobile number" name="visit-phone" value={form.phone} onChange={v=>setForm(x=>({...x,phone:v.replace(/\D/g,"").slice(0,10)}))} required placeholder="10-digit mobile"/><Field label="Email (optional)" name="visit-email" type="email" value={form.email} onChange={v=>setForm(x=>({...x,email:v}))} placeholder="you@example.com"/><Field label="Preferred date" name="visit-date" type="date" value={form.date} onChange={v=>setForm(x=>({...x,date:v}))} required/><Field label="Preferred time" name="visit-time" type="time" value={form.time} onChange={v=>setForm(x=>({...x,time:v}))} required/><div className="field full"><label htmlFor="visit-product-v2">Product</label><select id="visit-product-v2" value={form.productId} onChange={e=>setForm(x=>({...x,productId:e.target.value}))}><option value="">Open to recommendations</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div></div>{error&&<div className="error-text" style={{marginTop:12}}>{error}</div>}<button className="button button-light button-block" disabled={busy} type="submit">{busy?"Registering…":"Get my visit reference"} <ArrowRight size={14}/></button><p style={{marginBottom:0,color:"rgba(255,255,255,.48)",fontSize:".67rem",lineHeight:1.5}}>Your reference expires according to the store's configured validity period.</p></form></div></div></section><style>{styles}</style></>;
}
const styles=`.visit-success{background:#152326;color:#fff;border-radius:24px;padding:34px;text-align:center;box-shadow:0 18px 50px rgba(15,30,33,.15)}.visit-success h1{font-size:38px;letter-spacing:-.04em;margin:8px 0 10px}.visit-success p{max-width:580px;margin:0 auto 20px;color:rgba(255,255,255,.68);line-height:1.6}.visit-discount{font-size:28px;font-weight:900;color:#ff8b72}.visit-discount small{display:block;font-size:9px;letter-spacing:.14em;text-transform:uppercase;color:rgba(255,255,255,.45);margin-top:3px}.visit-pass-meta{display:flex;justify-content:center;gap:18px;flex-wrap:wrap;color:rgba(255,255,255,.62);font-size:11px;margin:20px 0}.visit-pass-meta span{display:flex;gap:6px;align-items:center}.visit-qr{width:170px;height:170px;border:1px solid rgba(255,255,255,.12);border-radius:18px;margin:18px auto;display:grid;place-items:center;align-content:center;gap:5px;background:rgba(255,255,255,.04)}.visit-qr span{font:9px monospace;color:rgba(255,255,255,.55)}@media(max-width:650px){.visit-success{padding:24px 16px}.visit-success h1{font-size:29px}.visit-pass-meta{display:grid;justify-items:center}.visit-qr{width:145px;height:145px}}`;
