import { useEffect, useRef, useState } from "react";
import { ChevronRight, Instagram, MapPin, Menu, MessageCircle, Search, ShoppingBag, X } from "lucide-react";
import { Link, NavLink, useLocation } from "react-router-dom";
import { useApp } from "../app/AppContext";
import { Logo } from "./Ui";

const navigation=[["Shop","/shop"],["New in","/shop?sort=new"],["Running","/category/running"],["Everyday","/category/everyday"],["Outdoor","/category/outdoor"],["Track order","/track-order"]] as const;
const whatsappHref=(phone:string,text:string)=>`https://wa.me/${phone.replace(/\D/g,"")||"919000000000"}?text=${encodeURIComponent(text)}`;
const field=(...names:string[])=>{for(const n of names){const el=document.querySelector<HTMLInputElement | HTMLTextAreaElement>(`[name="${n}"]`);if(el?.value?.trim())return el.value.trim()}return ""};
function CheckoutWhatsAppRequest({phone}:{phone:string}){const location=useLocation();if(location.pathname!=="/checkout"||!phone)return null;const request=()=>{const name=field("name","customerName"),mobile=field("phone","customerPhone"),email=field("email","customerEmail"),address=field("addressLine1","address","street"),city=field("city"),state=field("state"),pin=field("postalCode","pincode","pinCode");const text=[`Hello Rider Shoes, I want delivery assistance.`,`Name: ${name||"Not provided"}`,`Mobile: ${mobile||"Not provided"}`,`Email: ${email||"Not provided"}`,`Address: ${address||"Not provided"}`,`City: ${city||"Not provided"}`,`State: ${state||"Not provided"}`,`Pincode: ${pin||"Not provided"}`,`Please confirm whether you can deliver to this address.`].join("\n");window.open(whatsappHref(phone,text),"_blank","noopener,noreferrer")};return <button type="button" onClick={request} className="checkout-whatsapp-request"><MessageCircle size={17}/><span><b>Area not supported?</b><small>Request delivery on WhatsApp</small></span></button>}
export function SiteHeader(){const {settings,cart}=useApp();const [open,setOpen]=useState(false);const headerRef=useRef<HTMLElement|null>(null);useEffect(()=>{if(!open)return;const onPointerDown=(e:PointerEvent)=>{const target=e.target as Node|null;if(target&&!headerRef.current?.contains(target))setOpen(false)};const onKey=(e:KeyboardEvent)=>{if(e.key==="Escape")setOpen(false)};document.addEventListener("pointerdown",onPointerDown);document.addEventListener("keydown",onKey);return()=>{document.removeEventListener("pointerdown",onPointerDown);document.removeEventListener("keydown",onKey)}},[open]);return <header ref={headerRef} className={`site-header ${location.pathname==="/"?"dark":""}`}>{settings.announcementEnabled&&<div className="announcement"><strong>{settings.announcementText}</strong> · Thoughtful footwear for everyday movement</div>}<div className="container-wide header-inner"><button className="icon-button mobile-menu-button" onClick={()=>setOpen(x=>!x)} aria-label="Menu" aria-expanded={open}>{open?<X size={18}/>:<Menu size={18}/>}</button><Logo light={location.pathname==="/"}/><nav className={`desktop-nav ${open?"open":""}`}>{navigation.map(([label,href])=><NavLink key={href} to={href} onClick={()=>setOpen(false)} className={({isActive})=>isActive?"active":""}>{label}</NavLink>)}</nav><div className="header-actions"><Link className="icon-button hide-mobile" to="/shop" aria-label="Search"><Search size={17}/></Link><Link className="icon-button has-count" to="/cart" aria-label="Shopping bag"><ShoppingBag size={17}/>{cart.length>0&&<span className="count-pill">{cart.reduce((s,x)=>s+x.quantity,0)}</span>}</Link></div></div></header>}
export function SiteFooter(){const {settings}=useApp();return <footer className="site-footer"><div className="container-wide"><div className="footer-grid"><div><Logo light/><p>{settings.description}</p><div style={{display:"flex",gap:8,marginTop:18}}>{settings.instagramUrl&&<a className="icon-button" href={settings.instagramUrl} target="_blank" rel="noreferrer" aria-label="Instagram"><Instagram size={15}/></a>}<a className="icon-button" href={`tel:${settings.supportPhone}`} aria-label="Call Rider Shoes"><MessageCircle size={15}/></a><a className="icon-button" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${settings.addressLine1}, ${settings.city}`)}`} target="_blank" rel="noreferrer" aria-label="Find store"><MapPin size={15}/></a></div></div><div><h3>Explore</h3><div className="footer-links"><Link to="/shop">All shoes</Link><Link to="/shop?sort=new">New in</Link><Link to="/shop?sort=featured">Featured</Link><Link to="/offers">Offers</Link></div></div><div><h3>Help</h3><div className="footer-links"><Link to="/track-order">Track my order</Link><a href={whatsappHref(settings.supportWhatsappNumber||settings.supportPhone,"Hello Rider Shoes, I want to track my order.")} target="_blank" rel="noreferrer">Track order on WhatsApp</a><Link to="/contact">Contact</Link><Link to="/refund-policy">Returns</Link></div></div><div><h3>Legal</h3><div className="footer-links"><Link to="/about">Our story</Link><Link to="/privacy">Privacy</Link><Link to="/terms">Terms</Link></div></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} {settings.storeName}. Built for every step.</span><span>{settings.city}, {settings.state} · {settings.storeHours}</span></div></div></footer>}
export function StoreContactBar(){const {settings}=useApp();return <div style={{display:"flex",flexWrap:"wrap",gap:15,color:"var(--muted)",fontSize:".72rem"}}><span style={{display:"inline-flex",alignItems:"center",gap:6}}><MapPin size={14} color="var(--coral)"/>{settings.city}, {settings.state}</span><span style={{display:"inline-flex",alignItems:"center",gap:6}}><MessageCircle size={14} color="var(--coral)"/>{settings.supportPhone}</span></div>}
export function FloatingWhatsApp(){const {settings}=useApp();if(!settings.supportWhatsappEnabled&&!settings.supportWhatsappNumber)return null;return <a className="floating-whatsapp" href={whatsappHref(settings.supportWhatsappNumber||settings.supportPhone,`Hello ${settings.storeName}, I need help with a pair of shoes.`)} target="_blank" rel="noreferrer" aria-label="Chat on WhatsApp"><MessageCircle size={25}/></a>}
export function Breadcrumbs({current}:{current:string}){return <div className="container-wide" style={{paddingTop:20,color:"var(--muted)",fontSize:".7rem",display:"flex",alignItems:"center",gap:7}}><Link to="/">Home</Link><ChevronRight size={13}/>{current}</div>}
export function CustomerShell({children}:{children:React.ReactNode}){const {settings}=useApp();return <div className="page-shell"><SiteHeader/><CheckoutWhatsAppRequest phone={settings.supportWhatsappNumber||settings.supportPhone}/>{children}<FloatingWhatsApp/><SiteFooter/></div>}
