import { motion, useReducedMotion } from "framer-motion";
import { type LucideIcon } from "lucide-react";
import { Link } from "react-router-dom";
import type { Category, Product } from "../types";

export function Logo({ light = false }: { light?: boolean }) { return <Link to="/" className="brand-lockup" aria-label="Rider Shoes home"><span className="brand-mark" style={light ? { color: "#fff" } : undefined}>R<span>I</span>DER</span><span className="brand-submark">SHOES</span></Link>; }
export function Reveal({children,delay=0,className=""}:{children:React.ReactNode;delay?:number;className?:string}){const reduced=useReducedMotion();return <motion.div className={className} initial={reduced?undefined:{opacity:0,y:24}} whileInView={reduced?undefined:{opacity:1,y:0}} viewport={{once:true,amount:.12}} transition={{duration:.62,delay,ease:[.22,1,.36,1]}}>{children}</motion.div>;}
export function SectionHeading({eyebrow,title,description,action}:{eyebrow?:string;title:string;description?:string;action?:React.ReactNode}){return <div className="section-head"><div>{eyebrow&&<div className="eyebrow">{eyebrow}</div>}<h2 className="display-title">{title}</h2></div>{description&&<p>{description}</p>}{action}</div>;}
export function Stars({rating=0,reviewCount}:{rating?:number;reviewCount?:number}){return null;}
export function ProductCard({product,index=0}:{product:Product;index?:number}){const discount=product.compareAtPrice&&product.compareAtPrice>product.price?Math.round((1-product.price/product.compareAtPrice)*100):0;return <Reveal delay={Math.min(index*.05,.2)}><Link data-card-version="clean-product-card" className="product-card" style={{border:"1px solid rgba(17,23,25,.16)",borderRadius:24}} to={`/product/${product.slug}`} aria-label={`View ${product.name}`}><div className="product-image-wrap"><img src={product.imageUrl} alt={product.images[0]?.altText??product.name} loading="lazy"/>{product.badge&&<span className="product-badge">{product.badge}</span>}</div><div className="product-copy"><div className="product-brand">{product.brand?.name??"Rider collection"}</div><h3>{product.name}</h3><p>{product.shortDescription}</p><div className="price-row"><span className="price">₹{product.price.toLocaleString("en-IN")}</span>{product.compareAtPrice&&<span className="compare">₹{product.compareAtPrice.toLocaleString("en-IN")}</span>}{discount>0&&<span className="discount">{discount}% off</span>}</div></div></Link></Reveal>;}
export function CategoryCard({category,index=0}:{category:Category;index?:number}){return <Reveal delay={index*.06}><Link className="category-card" to={`/category/${category.slug}`} style={{borderRadius:30,border:"1px solid rgba(255,255,255,.32)",boxShadow:"0 16px 34px rgba(16,25,28,.14)"}}><img src={category.imageUrl} alt={`${category.name} shoes`} loading="lazy"/><div className="category-copy"><h3>{category.name}</h3><p>{category.description}</p></div></Link></Reveal>;}
export function TrustCard({icon:Icon,title,text}:{icon:LucideIcon;title:string;text:string}){return <Reveal><div className="trust-card"><div className="trust-icon"><Icon size={19}/></div><h3>{title}</h3><p>{text}</p></div></Reveal>;}
export function PageLoader(){return <div className="section"><div className="container-wide"><div className="skeleton" style={{height:360,borderRadius:26}}/></div></div>}
export function EmptyState({icon:Icon,title,description,action}:{icon:LucideIcon;title:string;description:string;action?:React.ReactNode}){return <div className="empty-state"><Icon size={33}/><h2>{title}</h2><p>{description}</p>{action}</div>;}
export function Field({label,name,value,onChange,type="text",placeholder,required=false,full=false,min,max}:{label:string;name:string;value:string|number;onChange:(value:string)=>void;type?:string;placeholder?:string;required?:boolean;full?:boolean;min?:string;max?:string}){return <div className={`field ${full?"full":""}`}><label htmlFor={name}>{label}{required?" *":""}</label><input id={name} name={name} type={type} value={value} onChange={event=>onChange(event.target.value)} placeholder={placeholder} required={required} min={min} max={max}/></div>;}
export function SocialIcon({icon:Icon,label,href}:{icon:LucideIcon;label:string;href:string}){return <a className="icon-button" href={href} aria-label={label} target="_blank" rel="noreferrer"><Icon size={16}/></a>;}
