/** JSON values accepted by Supabase json/jsonb columns. */
export type Json = string | number | boolean | null | Json[] | { [key: string]: Json | undefined };
export type JsonObject = { [key: string]: Json | undefined };
export type ISODateString = string;
export type CurrencyCode = string;
export type ProductStatus = "draft" | "active" | "archived";
export interface BrandSummary { id:string; slug:string; name:string; }
export interface Category { id:string; parentId:string|null; slug:string; name:string; description:string; imageUrl:string; sortOrder:number; isActive:boolean; seoTitle:string|null; seoDescription:string|null; productCount:number|null; createdAt:ISODateString; updatedAt:ISODateString; }
export interface ProductImage { id:string; url:string; altText:string; sortOrder:number; isPrimary:boolean; }
export interface ProductVariant { id:string; productId:string; sku:string; size:string|null; color:string|null; optionValues:JsonObject; price:number; compareAtPrice:number|null; currency:CurrencyCode; weightGrams:number|null; isActive:boolean; stockQuantity:number|null; }
export interface Product { id:string; slug:string; name:string; shortDescription:string; description:string; status:ProductStatus; taxRate:number; brand:BrandSummary|null; categoryIds:string[]; primaryCategoryId:string|null; images:ProductImage[]; variants:ProductVariant[]; metadata:JsonObject; price:number; compareAtPrice:number|null; currency:CurrencyCode; imageUrl:string; sizes:string[]; colors:string[]; tags:string[]; featured:boolean; isNew:boolean; badge:string|null; rating:number|null; reviewCount:number; inStock:boolean; createdAt:ISODateString; updatedAt:ISODateString; }
export interface CartItem { id:string; productId:string; variantId:string; productName:string; productSlug:string; imageUrl:string; sku:string; size:string|null; color:string|null; unitPrice:number; currency:CurrencyCode; quantity:number; addedAt:ISODateString; }
export interface WishlistItem { productId:string; addedAt:ISODateString; }
export interface Address { recipientName:string; phone:string; addressLine1:string; addressLine2:string; city:string; state:string; postalCode:string; countryCode:string; }
export interface OrderCustomer { name:string; email:string; phone:string; }
export type OrderStatus = "pending"|"payment_pending"|"confirmed"|"processing"|"packed"|"shipped"|"out_for_delivery"|"delivered"|"cancelled"|"refund_requested"|"returned"|"refunded";
export type PaymentStatus = "pending"|"authorized"|"paid"|"failed"|"partially_refunded"|"refunded";
export type FulfillmentStatus = "unfulfilled"|"partially_fulfilled"|"fulfilled"|"returned";
export type PaymentMethod = "razorpay"|"cod"|"other";
export interface OrderItem { id:string; productId:string|null; variantId:string|null; productName:string; productSlug:string|null; imageUrl:string; sku:string|null; size:string|null; color:string|null; quantity:number; unitPrice:number; discountAmount:number; taxAmount:number; lineTotal:number; }
export interface Order { id:string; orderNumber:string; customer:OrderCustomer; items:OrderItem[]; status:OrderStatus; paymentStatus:PaymentStatus; fulfillmentStatus:FulfillmentStatus; paymentMethod:PaymentMethod; currency:CurrencyCode; subtotal:number; discountTotal:number; taxTotal:number; shippingTotal:number; totalAmount:number; amountPaid:number; amountRefunded:number; shippingAddress:Address; billingAddress:Address; customerNote:string; trackingNumber:string|null; placedAt:ISODateString; paidAt:ISODateString|null; cancelledAt:ISODateString|null; createdAt:ISODateString; updatedAt:ISODateString; }
export interface BusinessSettings { storeName:string; tagline:string; description:string; logoUrl:string; currency:CurrencyCode; locale:string; taxIncluded:boolean; supportEmail:string; supportPhone:string; supportWhatsappEnabled:boolean; supportWhatsappNumber:string; addressLine1:string; addressLine2:string; city:string; state:string; postalCode:string; countryCode:string; freeShippingThreshold:number; standardShippingFee:number; deliveryEstimate:string; returnsWindowDays:number; announcementEnabled:boolean; announcementText:string; heroTitle:string; heroSubtitle:string; heroImageUrl:string; heroButtonLabel:string; heroButtonUrl:string; primaryColor:string; secondaryColor:string; colorMode:"light"|"dark"|"system"; instagramUrl:string; facebookUrl:string; youtubeUrl:string; mapsUrl:string; storeHours:string; seoTitle:string; seoDescription:string; onlineOrdersEnabled:boolean; codEnabled:boolean; codMin:number; codMax:number; codFee:number; storeVisitEnabled:boolean; storeVisitDiscount:number; storeVisitDiscountType:"percent"|"fixed"; storeVisitValidityDays:number; storeVisitTerms:string; whatsappAutomationEnabled:boolean; }
export interface DeliveryQuote { serviceable:boolean; shippingFee:number; freeShippingThreshold:number|null; estimatedDaysMin:number; estimatedDaysMax:number; }
export interface CustomerProfile { id:string; email:string|null; fullName:string; phone:string; avatarUrl:string|null; isActive:boolean; metadata:JsonObject; createdAt:ISODateString; updatedAt:ISODateString; }
export interface DeliveryArea { id:string; name:string; countryCode:string; state:string|null; city:string|null; postalCode:string|null; shippingFee:number; freeShippingThreshold:number|null; estimatedDaysMin:number; estimatedDaysMax:number; isActive:boolean; }
export interface StoreVisit { id:string; profileId:string|null; sessionIdHash:string|null; path:string; referrer:string|null; userAgent:string|null; metadata:JsonObject; occurredAt:ISODateString; }
export interface AdminMetrics { currency:string; totalRevenue:number; totalOrders:number; totalCustomers:number; totalVisits:number; conversionRate:number; averageOrderValue:number; activeProducts:number; lowStockProducts:number; pendingOrders:number; revenueChangePercent:number; ordersChangePercent:number; customersChangePercent:number; visitsChangePercent:number; salesSeries:{label:string;value:number}[]; visitsSeries:{label:string;value:number}[]; topProducts:{name:string;unitsSold:number;revenue:number}[]; }
export type DbProductRow=any; export type DbProductVariantRow=any; export type DbProductImageRow=any; export type DbProductCategoryRow=any; export type DbCategoryRow=any; export type DbBrandRow=any; export type DbBusinessSettingRow=any;
